#!/bin/bash

# if [ <some test> ]
# then
#   <commands>
# fi

# if [ <some test> ]
# then
#   <commands>
# else
#   <other commands>
# fi

# ! EXPRESSION	            The EXPRESSION is false.
# -n STRING	                length of STRING is greater than zero.
# -z STRING	                length of STRING is zero (ie. it is empty).
# STRING1 = STRING2	        STRING1 is equal to STRING2
# STRING1 != STRING2	    STRING1 is not equal to STRING2
# INTEGER1 -eq INTEGER2	    INTEGER1 is numerically equal to INTEGER2
# INTEGER1 -gt INTEGER2	    INTEGER1 is numerically greater than INTEGER2
# INTEGER1 -lt INTEGER2	    INTEGER1 is numerically less than INTEGER2
# -d FILE	                FILE exists and is a directory.
# -e FILE	                FILE exists.
# -r FILE	                FILE exists and the read permission is granted.
# -s FILE	                FILE exists and it's size is greater than zero (ie. it is not empty).
# -w FILE	                FILE exists and the write permission is granted.
# -x FILE	                FILE exists and the execute permission is granted.

if [ $# -eq 1 ]
then
    nl $1
else
    nl /dev/stdin
fi
